version: '2'
services:
  briob-mysql:
    restart: always
    container_name: briob-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
  delivery-service:
    restart: on-failure
    build: ./
    expose:
      - "8086"
    ports:
      - 8086:8086
    environment:
      WAIT_HOSTS: briob-mysql:3306
    depends_on:
      - briob-mysql